# GitHub Pages Configuration
# Cynteo Alert Bridge Documentation Site

# Site settings
title: Cynteo Alert Bridge Documentation
description: Connect Azure Monitor alerts to SolarWinds Service Desk automatically
baseurl: "" # Leave empty if using custom domain or org.github.io/repo-name
url: "https://cynteocloud.github.io" # Update with your actual GitHub Pages URL

# Theme
theme: jekyll-theme-cayman
# Alternative themes:
# - jekyll-theme-minimal
# - jekyll-theme-slate
# - jekyll-theme-modernist

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Navigation
nav:
  - name: Home
    link: /
  - name: Quick Start
    link: /getting-started/quickstart
  - name: Guides
    link: /guides/
  - name: Troubleshooting
    link: /troubleshooting/common-issues
  - name: Reference
    link: /reference/

# Footer
footer_links:
  - name: Support
    url: mailto:support@cynteocloud.com
  - name: Website
    url: https://cynteocloud.com
  - name: Azure Marketplace
    url: https://azuremarketplace.microsoft.com

# SEO
author: Cynteo Cloud
twitter:
  username: cynteocloud # Update with actual handle
  card: summary_large_image

# Social links
social_links:
  - platform: GitHub
    url: https://github.com/cynteocloud
  - platform: LinkedIn
    url: https://linkedin.com/company/cynteo

# Analytics (optional)
# google_analytics: UA-XXXXXXXXX-X

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author: Cynteo Cloud

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

# Include
include:
  - _config.yml

# Permalinks
permalink: pretty

# Collections (if you add them later)
collections:
  guides:
    output: true
    permalink: /guides/:name
  troubleshooting:
    output: true
    permalink: /troubleshooting/:name

# Build settings
safe: true
lsi: false
incremental: false

